# -*- coding: utf-8 -*-
"""streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qHpuR0FKBOe1tSx3gebzxCwAxr-047yQ
"""

pip install streamlit

pip show streamlit